-- 코드를 작성해주세요
WITH P AS (
    SELECT ID, SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
)
SELECT ID, 
    CASE 
        WHEN PER=1 THEN 'CRITICAL'
        WHEN PER=2 THEN 'HIGH'
        WHEN PER=3 THEN 'MEDIUM'
        WHEN PER=4 THEN 'LOW'
    END AS COLONY_NAME
FROM P
ORDER BY ID